<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Presistence\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TaskManagerApi.Application\TaskManagerApi.Application.csproj" />
      <ProjectReference Include="..\TaskManagerApi.Domain\TaskManagerApi.Domain.csproj" />
    </ItemGroup>

</Project>
